import { Check, RotateCcw, Sparkles, WandSparkles } from "lucide-react";
import { useMemo, useState } from "react";

const COLORS = [["Pudrová", "#E8B5AC"], ["Starorůžová", "#B97978"], ["Mléčná", "#F8F2ED"], ["Pistácie", "#9DAA91"], ["Šalvěj", "#647663"], ["Višňová", "#A83E49"], ["Čokoláda", "#5A3C34"], ["Švestka", "#6D507F"], ["Modrá", "#5D849A"], ["Zlatá", "#C8A160"], ["Stříbrná", "#B8BBC0"], ["Onyx", "#26272A"]] as const;
const SHAPES = ["Mandle", "Ovál", "Square", "Stiletto", "Coffin"];
const LENGTHS = ["Krátká", "Střední", "Dlouhá"];
const FINISHES = ["Lesk", "Velvet mat", "Glazed", "Ombré", "Chrom", "Třpyt"];
const DECORATIONS = ["Bez zdobení", "Kamínky", "3D květy", "Mašličky", "Hvězdičky", "Srdíčka", "Zlatá linka"];
const FINGERS = ["Levý palec", "Levý ukazováček", "Levý prostředníček", "Levý prsteníček", "Levý malíček", "Pravý palec", "Pravý ukazováček", "Pravý prostředníček", "Pravý prsteníček", "Pravý malíček"];
const NAIL_POSITIONS = [[45.7, 42.4, 43], [20.4, 66.8, -10], [30.2, 72.7, -8], [39.1, 74.6, -3], [46.6, 69.8, 10], [54.3, 42.4, -43], [79.6, 66.8, 10], [69.8, 72.7, 8], [60.9, 74.6, 3], [53.4, 69.8, -10]] as const;
type Props = { onDescriptionChange?: (description: string) => void };

export default function NailDesignStudio({ onDescriptionChange }: Props) {
  const [selected, setSelected] = useState(7);
  const [nails, setNails] = useState(Array(10).fill("#E8B5AC"));
  const [shape, setShape] = useState("Mandle"); const [length, setLength] = useState("Střední"); const [finish, setFinish] = useState("Lesk"); const [decoration, setDecoration] = useState("Bez zdobení"); const [ready, setReady] = useState(false);
  const description = (next?: Partial<{ shape: string; length: string; finish: string; decoration: string; nails: string[] }>) => { const used = [...new Set(next?.nails ?? nails)].map((color) => COLORS.find(([, value]) => value === color)?.[0] ?? "vlastní barva"); return `${next?.shape ?? shape}, ${(next?.length ?? length).toLowerCase()} délka, ${(next?.finish ?? finish).toLowerCase()}, ${used.join(" a ").toLowerCase()}, ${(next?.decoration ?? decoration).toLowerCase()}`; };
  const summary = useMemo(() => description(), [decoration, finish, length, nails, shape]);
  const setOption = (kind: "shape" | "length" | "finish" | "decoration", value: string) => { setReady(false); if (kind === "shape") setShape(value); if (kind === "length") setLength(value); if (kind === "finish") setFinish(value); if (kind === "decoration") setDecoration(value); onDescriptionChange?.(description({ [kind]: value })); };
  const paint = (color: string) => { setReady(false); const next = nails.map((value, index) => index === selected ? color : value); setNails(next); onDescriptionChange?.(description({ nails: next })); };
  const reset = () => { const base = Array(10).fill("#E8B5AC"); setNails(base); setSelected(7); setShape("Mandle"); setLength("Střední"); setFinish("Lesk"); setDecoration("Bez zdobení"); setReady(false); onDescriptionChange?.("Mandlový tvar, střední délka, lesk, pudrová, bez zdobení"); };
  return <section className="overflow-hidden rounded-[28px] border border-[#e6cdc3] bg-[#fffaf7] shadow-[0_22px_55px_-40px_rgba(78,51,43,.55)]" data-testid="interactive-nail-designer">
    <header className="flex items-center justify-between border-b border-[#eeddd5] bg-[#fff7f2] px-4 py-3 sm:px-6"><div><p className="flex items-center gap-2 font-heading text-base tracking-[.08em] text-[#63463d] uppercase"><Sparkles className="size-4 text-[#c38575]" /> Návrhářství nehtů</p><p className="mt-0.5 text-[11px] text-[#967d73]">Klepněte na nehet ve fotografii a vytvořte vlastní design.</p></div><button onClick={reset} type="button" className="inline-flex items-center gap-1.5 rounded-full border border-[#e7d0c6] bg-white px-3 py-1.5 text-[10px] font-medium tracking-[.12em] text-[#89685e] uppercase hover:bg-[#f9ede7]"><RotateCcw className="size-3" /> Reset</button></header>
    <div className="grid items-start xl:grid-cols-[1.08fr_.92fr]"><div className="relative h-fit self-start bg-[#f5ddd8] p-3 sm:p-5"><div className="relative mx-auto max-w-[680px] overflow-hidden rounded-[22px] border border-white/80 shadow-[0_18px_36px_-26px_rgba(76,45,37,.65)]"><img src="/nehty/interactive-hands-base-v1.png" alt="Dvě ruce připravené pro návrh manikúry" className="block w-full select-none" draggable="false" />{NAIL_POSITIONS.map(([left, top, rotate], index) => <button key={FINGERS[index]} type="button" aria-label={`${FINGERS[index]}: vybrat nehet`} onClick={() => { setSelected(index); setReady(false); }} className={`photo-nail ${selected === index ? "is-selected" : ""}`} style={{ left: `${left}%`, top: `${top}%`, transform: `translate(-50%, -50%) rotate(${rotate}deg)` } as React.CSSProperties} />)}</div><p className="mx-auto mt-3 max-w-[680px] rounded-xl border border-white/75 bg-white/50 px-3 py-2 text-center text-[11px] text-[#6f5147]"><span className="mr-1.5 inline-block size-1.5 animate-pulse rounded-full bg-[#8b9a85]" /> Vybraný nehet: <strong>{FINGERS[selected]}</strong> · klepněte na jiný nehet, chcete-li jej upravit samostatně.</p></div>
      <div className="space-y-4 p-4 sm:p-6"><div className="flex items-center gap-3 rounded-2xl border border-[#e8d7cf] bg-[#fffaf7] p-3"><span className="size-9 rounded-full border-2 border-white shadow-sm" style={{ backgroundColor: nails[selected] }} /><div><p className="text-[10px] font-medium tracking-[.14em] text-[#9b776b] uppercase">Upravujete</p><p className="text-sm text-[#654a42]">{FINGERS[selected]}</p></div></div><GameChoices label="1 · Barva pro vybraný nehet" className="grid grid-cols-6 gap-2">{COLORS.map(([name, color]) => <button key={name} type="button" onClick={() => paint(color)} title={name} aria-label={name} className={`size-8 rounded-full border-2 transition duration-200 hover:scale-110 ${nails[selected] === color ? "border-[#61453d] ring-2 ring-[#c99886]/40" : "border-white shadow-sm"}`} style={{ backgroundColor: color }} />)}</GameChoices><GameChoices label="2 · Tvar"><Chips values={SHAPES} value={shape} onClick={(value) => setOption("shape", value)} /></GameChoices><GameChoices label="3 · Délka"><Chips values={LENGTHS} value={length} onClick={(value) => setOption("length", value)} /></GameChoices><GameChoices label="4 · Finiš"><Chips values={FINISHES} value={finish} onClick={(value) => setOption("finish", value)} /></GameChoices><GameChoices label="5 · Zdobení"><Chips values={DECORATIONS} value={decoration} onClick={(value) => setOption("decoration", value)} /></GameChoices><div className={`rounded-2xl border p-3 transition-colors ${ready ? "border-[#a5b398] bg-[#f0f5ed]" : "border-[#ecd8cf] bg-[#fbf2ed]"}`}><p className="text-[10px] font-medium tracking-[.14em] text-[#9b776b] uppercase">Váš návrh pro nail artistu</p><p className="mt-1 text-xs leading-relaxed text-[#654a42]">{summary}</p></div><button type="button" onClick={() => { setReady(true); onDescriptionChange?.(summary); }} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#8b9a85] px-4 py-3 text-xs font-medium tracking-[.13em] text-white uppercase transition hover:bg-[#798a73]"><WandSparkles className="size-4" /> Připravit můj návrh</button>{ready && <button type="button" onClick={() => document.getElementById("rezervace")?.scrollIntoView({ behavior: "smooth" })} className="flex w-full items-center justify-center gap-1 text-xs font-medium tracking-[.08em] text-[#758b70]"><Check className="size-4" /> Návrh je připravený · pokračovat k rezervaci</button>}</div></div>
  </section>;
}
function GameChoices({ label, className, children }: { label: string; className?: string; children: React.ReactNode }) { return <div><p className="mb-2 text-[10px] font-medium tracking-[.17em] text-[#a08479] uppercase">{label}</p><div className={className ?? "flex flex-wrap gap-1.5"}>{children}</div></div>; }
function Chips({ values, value, onClick }: { values: string[]; value: string; onClick: (value: string) => void }) { return <>{values.map((item) => <button type="button" key={item} onClick={() => onClick(item)} className={`rounded-full border px-2.5 py-1.5 text-[10px] transition ${value === item ? "border-[#8b9a85] bg-[#8b9a85] text-white shadow-sm" : "border-[#ead8d0] bg-white text-[#795b51] hover:border-[#c58c7e]"}`}>{item}</button>)}</>; }
